In [1]:
import pandas as pd

internet_usage_df = pd.read_csv("share-of-individuals-using-the-internet.csv")
internet_usage_df

          Country Code  Year  Individuals using the Internet (% of population)
0     Afghanistan  AFG  1990                                          0.000000
1     Afghanistan  AFG  2001                                          0.004723
2     Afghanistan  AFG  2002                                          0.004561
3     Afghanistan  AFG  2003                                          0.087891
4     Afghanistan  AFG  2004                                          0.105809
...           ...  ...   ...                                               ...
6051     Zimbabwe  ZWE  2012                                         12.000000
6052     Zimbabwe  ZWE  2013                                         15.500000
6053     Zimbabwe  ZWE  2014                                         16.364740
6054     Zimbabwe  ZWE  2015                                         22.742818
6055     Zimbabwe  ZWE  2016                                         23.119989

[6056 rows x 4 columns]

In [2]:
internet_usage_2016 = internet_usage_df.query("Year==2016")
internet_usage_2016

,Country,Code,Year,Individuals using the Internet (% of population)
16,Afghanistan,AFG,2016,10.595726
39,Albania,ALB,2016,66.363445
63,Algeria,DZA,2016,42.945527
85,Andorra,AND,2016,97.930637
107,Angola,AGO,2016,13.000000
...,...,...,...,...
5960,Vietnam,VNM,2016,46.500000
5985,World,OWID_WRL,2016,45.793684
6007,Yemen,YEM,2016,24.579208
6031,Zambia,ZMB,2016,25.506579
6055,Zimbabwe,ZWE,2016,23.119989

In [3]:
import plotly.express as px

fig = px.choropleth(internet_usage_2016,
                    locations="Code",
                    color="Individuals using the Internet (% of population)",
                    hover_name="Country",
                    color_continuous_scale=px.colors.sequential.Plasma)

fig.update_layout(title_text = 'Internet usage across the world (% population) - 2016',
                  geo = dict(projection = {'type':'natural earth'}))

fig.show()

In [7]:
import plotly.express as px
fig = px.choropleth(internet_usage_2016,
                    locations="Code",
                    color="Individuals using the Internet (% of population)",
                    hover_name="Country",
                    color_continuous_scale=px.colors.sequential.Plasma)

# add a title text for the plot
fig.update_layout(title_text = 'Internet usage across the world (% population) - 2016',
                   geo_scope = 'asia')
# can be set to north america | south america | africa | asia | europe | usa

fig.show()