In [9]:
import pandas as pd

internet_usage_df = pd.read_csv("share-of-individuals-using-the-internet.csv")
internet_usage_df

          Country Code  Year  Individuals using the Internet (% of population)
0     Afghanistan  AFG  1990                                          0.000000
1     Afghanistan  AFG  2001                                          0.004723
2     Afghanistan  AFG  2002                                          0.004561
3     Afghanistan  AFG  2003                                          0.087891
4     Afghanistan  AFG  2004                                          0.105809
...           ...  ...   ...                                               ...
6051     Zimbabwe  ZWE  2012                                         12.000000
6052     Zimbabwe  ZWE  2013                                         15.500000
6053     Zimbabwe  ZWE  2014                                         16.364740
6054     Zimbabwe  ZWE  2015                                         22.742818
6055     Zimbabwe  ZWE  2016                                         23.119989

[6056 rows x 4 columns]

In [2]:
internet_usage_2016 = internet_usage_df.query("Year==2016")
internet_usage_2016

,Country,Code,Year,Individuals using the Internet (% of population)
16,Afghanistan,AFG,2016,10.595726
39,Albania,ALB,2016,66.363445
63,Algeria,DZA,2016,42.945527
85,Andorra,AND,2016,97.930637
107,Angola,AGO,2016,13.000000
...,...,...,...,...
5960,Vietnam,VNM,2016,46.500000
5985,World,OWID_WRL,2016,45.793684
6007,Yemen,YEM,2016,24.579208
6031,Zambia,ZMB,2016,25.506579
6055,Zimbabwe,ZWE,2016,23.119989

In [3]:
import plotly.express as px

fig = px.choropleth(internet_usage_2016,
                    locations="Code",
                    color="Individuals using the Internet (% of population)",
                    hover_name="Country",
                    color_continuous_scale=px.colors.sequential.Plasma)

fig.update_layout(title_text = 'Internet usage across the world (% population) - 2016',
                  geo = dict(projection = {'type':'natural earth'}))

fig.show()

In [7]:
import plotly.express as px
fig = px.choropleth(internet_usage_2016,
                    locations="Code",
                    color="Individuals using the Internet (% of population)",
                    hover_name="Country",
                    color_continuous_scale=px.colors.sequential.Plasma)

# add a title text for the plot
fig.update_layout(title_text = 'Internet usage across the world (% population) - 2016',
                   geo_scope = 'asia')
# can be set to north america | south america | africa | asia | europe | usa

fig.show()

In [11]:
internet_usage_df.head()

       Country Code  Year  Individuals using the Internet (% of population)
0  Afghanistan  AFG  1990                                          0.000000
1  Afghanistan  AFG  2001                                          0.004723
2  Afghanistan  AFG  2002                                          0.004561
3  Afghanistan  AFG  2003                                          0.087891
4  Afghanistan  AFG  2004                                          0.105809

In [14]:
import plotly.express as px
fig = px.choropleth(internet_usage_df,
                    locations="Code",
                    color="Individuals using the Internet (% of population)",
                    hover_name="Country",
                    animation_frame='Year',
                    color_continuous_scale=px.colors.sequential.Plasma)

fig.update_layout(title_text='Internet Usage across the world (% population)',
                 geo = dict(projection = {'type':'natural earth'}))

fig.show()

In [16]:
internet_usage_df_sorted = internet_usage_df.sort_values(by=["Year"])
internet_usage_df_sorted.head()

,Country,Code,Year,Individuals using the Internet (% of population)
5347,Syrian Arab Republic,NaN,1960,0.0
718,Burundi,BDI,1960,0.0
5493,Togo,TGO,1960,0.0
572,Botswana,BWA,1960,0.0
3414,Maldives,MDV,1960,0.0

In [17]:
import plotly.express as px
fig = px.choropleth(internet_usage_df_sorted,
                    locations="Code",
                    color="Individuals using the Internet (% of population)",
                    hover_name="Country",
                    animation_frame="Year", # column on which to animate !
                    color_continuous_scale=px.colors.sequential.Plasma)

fig.update_layout(title_text = 'Internet usage across the world (% population)',
                  geo = dict(projection = {'type' : 'natural earth'}))

fig.show()

In [18]:
import pandas as pd

df = pd.read_csv('us_state_population.tsv',sep='\t')
df.head()

,State,Code,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,Alabama,AL,4785448,4798834,4815564,4830460,4842481,4853160,4864745,4875120,4887871
1,Alaska,AK,713906,722038,730399,737045,736307,737547,741504,739786,737438
2,Arizona,AZ,6407774,6473497,6556629,6634999,6733840,6833596,6945452,7048876,7171646
3,Arkansas,AR,2921978,2940407,2952109,2959549,2967726,2978407,2990410,3002997,3013825
4,California,CA,37320903,37641823,37960782,38280824,38625139,38953142,39209127,39399349,39557045

In [19]:
df = pd.melt(df, id_vars=['State','Code'],
             var_name="Year",
             value_name="Population")
df

             State Code  Year  Population
0          Alabama   AL  2010     4785448
1           Alaska   AK  2010      713906
2          Arizona   AZ  2010     6407774
3         Arkansas   AR  2010     2921978
4       California   CA  2010    37320903
..             ...  ...   ...         ...
454       Virginia   VA  2018     8517685
455     Washington   WA  2018     7535591
456  West Virginia   WV  2018     1805832
457      Wisconsin   WI  2018     5813568
458        Wyoming   WY  2018      577737

[459 rows x 4 columns]

In [22]:
import plotly.graph_objects as go

fig = go.Figure(
               data=go.Choropleth(
               locations=df['Code'], # Code for US states
               z = df['Population'].astype(int), # Data to be color-coded
               locationmode = 'USA-states', # set of locations match entries in 'locations'
               #locationmode = 'ISO-3', # set of locations match entries in 'locations'
               colorscale = 'Blues',
               colorbar_title = "Population",
           )
)

fig.update_layout(
           title_text = 'US Population across states',
           geo_scope='usa'
           )
fig.show()

In [23]:
walmart_loc_df = pd.read_csv('1962_2006_walmart_store_openings.csv')
walmart_loc_df.head()

,storenum,OPENDATE,date_super,conversion,st,county,STREETADDR,STRCITY,STRSTATE,ZIPCODE,type_store,LAT,LON,MONTH,DAY,YEAR
0,1,7/1/62,3/1/97,1.0,5,7,2110 WEST WALNUT,Rogers,AR,72756,Supercenter,36.342235,-94.07141,7,1,1962
1,2,8/1/64,3/1/96,1.0,5,9,1417 HWY 62/65 N,Harrison,AR,72601,Supercenter,36.236984,-93.09345,8,1,1964
2,4,8/1/65,3/1/02,1.0,5,7,2901 HWY 412 EAST,Siloam Springs,AR,72761,Supercenter,36.179905,-94.50208,8,1,1965
3,8,10/1/67,3/1/93,1.0,5,29,1621 NORTH BUSINESS 9,Morrilton,AR,72110,Supercenter,35.156491,-92.75858,10,1,1967
4,7,10/1/67,NaN,NaN,5,119,3801 CAMP ROBINSON RD.,North Little Rock,AR,72118,Wal-Mart,34.813269,-92.30229,10,1,1967

In [25]:
import plotly.graph_objects as go
fig = go.Figure(data=go.Scattergeo(
    lon = walmart_loc_df['LON'],
    lat = walmart_loc_df['LAT'],
    text = walmart_loc_df['STREETADDR'],
    mode = 'markers'
    ))

fig.update_layout(
    title = 'Walmart stores across world',
    geo_scope='usa'
)

fig.show()